name = "RunwayLib"
uuid = "c31d23ff-e9b5-4186-8ef8-ce4d62614c67"
version = "0.1.0"
authors = ["Romeo Valentin <romeov@stanford.edu>"]

[deps]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
Moshi = "2e0e35c7-a2e4-4343-998d-7ef72827ed2d"
NonlinearSolveBase = "be0214bd-f91f-a760-ac4e-3421ce2b2da0"
NonlinearSolveFirstOrder = "5959db7a-ea39-4486-b5fe-2dd0bf03d60d"
Polyester = "f517fe37-dbe3-4b94-8317-1923a5111588"
PolyesterWeave = "1d0040c9-8b98-4ee7-8388-3f51789ca0ad"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
ProbabilisticParameterEstimators = "0098cf3f-3e1e-4f11-b01c-dd9dec1b3374"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TypedTables = "9d95f2ec-7b3d-5a63-8d20-e2491e220bb9"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"

[sources]
ForwardDiff = {rev = "rv/remove-quote-assert-string-interpolation", url = "https://github.com/RomeoV/ForwardDiff.jl.git"}
LinearSolve = {rev = "rv/allow-mmatrix-cache", url = "https://github.com/RomeoV/LinearSolve.jl"}
SciMLBase = {rev = "as/fix-jet-opt", url = "https://github.com/AayushSabharwal/SciMLBase.jl"}

[compat]
ADTypes = "1.16.0"
CEnum = "0.5.0"
DiffEqBase = "6.179.0"
ForwardDiff = "1.0.1"
LinearAlgebra = "1.11.0,1.12.0"
LinearSolve = "3.23.0"
Moshi = "0.3.7"
NonlinearSolveBase = "1.13.0"
NonlinearSolveFirstOrder = "1.7.0"
Polyester = "0.7.18"
PolyesterWeave = "0.2.2"
PrecompileTools = "1"
ProbabilisticParameterEstimators = "0.8.0,0.8.1,0.8.2"
SciMLBase = "2.102.1"
StatsBase = "0.34.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
